window.data1=[
    ["share Sudoku solver","https://studio.code.org/projects/applab/tq6f6xmxIqovL_yWTDpV0moGNpj5gC1yBz3GI2TfuII/edit","1/4/2025"],
    ["Binary Clock - MathEnthusiast314","https://studio.code.org/projects/applab/yk3e7kmByzzbixyx4zsC8_AnXJpSmnm8uozUwCpyKCU/edit","4/7/2023"],
    ["K Maps 2","https://studio.code.org/projects/applab/TlsrPjMWTiTWVvhnjx4R8fdNgk3n4Ht5T_vkUhxHLWU/edit","12/22/2022"],
    ["Exploring the universe","https://studio.code.org/projects/applab/4UKSctZTYKU9VNblcUUxLtTuNu4yAU3vBPiqeBEcpDM/edit","8/25/2021"],
    ["Final:Weather App","https://studio.code.org/projects/applab/GzxT43e2zd8V3bDaHglWFIhJ17Fu70csZPeKQHQ7Who/edit","3/23/2020"],
    ["Lights Out Game","https://studio.code.org/projects/applab/qlSdVVQrkwZ0jzpvpDeiwZ5reu-dNdoqi3VW0pzHjRw/edit","4/12/2020"],
    ["Systems of Equations using normal syntax","https://studio.code.org/projects/applab/F8cf7sdWAouRIpknq_GBQaXOVmPMeOnwm7b4k2cOvIc/edit","4/11/2020"],
    ["Remix: 3d Equation Evaluator trying draw lines","https://studio.code.org/projects/applab/HfGfcxBqYTo4vozZyqSinNlyIou7tOoqNuiAbIyb89U/edit","3/20/2020"],
    ["2d Graph","https://studio.code.org/projects/applab/kEUCxMdKd7P-a1y4zo4cO3IQasxWXeHipAoDwk1dS4w/edit","3/20/2020"],
    ["Connect Four for Login Multifeatured App","https://studio.code.org/projects/applab/r_RmJsgJ7GGUbgMHNkb7oSbNNgx4GP2wNOkYMqrB4_Q/edit","2/15/2020"],
    ["Final: SVG generator using Svg image(data:image) for Login Multifeatured App","https://studio.code.org/projects/applab/LrfR7bALNTQiJ9-zpnPCRNxt8aAAeAq8eyXyVuaxIFs/edit","3/10/2020"],
    ["Remix: Google Doodles","https://studio.code.org/projects/applab/KZWTTIuXEnXu3Pr2xf_yHJLXUyca_IEfCPA-VfcSVno/edit","3/8/2020"],
    ["concatenating Top View Images","https://studio.code.org/projects/applab/6EkvkpJAaFkqZi1H0zWDqFXmDKTdD1Wx7BJZu170Dxs/edit","11/12/2019"],
    ["Sudoku solver","https://studio.code.org/projects/applab/MKAGOH8k6Q3GK6Co_u69caCBc05ZXQJvUgYuRbr24Ek/edit","10/15/2018"],
    ["Ink Spill","https://studio.code.org/projects/applab/6W0jHpVDtTbcg3GhLOJrs-KI1c1P2Xo80bNtLBqHVzk/edit","6/9/2018"],
    ["Remix: Remix: rubix cube times with colors (testing universal solution rubik's cube)","https://studio.code.org/projects/applab/MWX0spUHAN6ab_j0Oke4OmSZ8AVKLi84O54mrnpkQWc/edit","2/17/2018"],
    ["Digit Recognition","https://studio.code.org/projects/applab/Y1SKRNCpLrCmJHGJQQgLkRSd-S41j2-usiLwq22Xcz8/edit","6/18/2018"],
    ["simple syntax_Bhavikscript","https://studio.code.org/projects/applab/80dITHu5tEplk2fSlE2lXFfcT2cpSFShBPEzeUD4h1s/edit","5/4/2018"],
    ["Digit Recognition (v2 neural networks)","https://studio.code.org/projects/applab/U3xrZTTV6yQCihkyPGEsR2lRPk5pPFaOiu3XWDNilXM/edit","1/23/2025"],
]
window.data2=[
    ["Calculator","https://studio.code.org/projects/applab/HbOG-QcnKVAqxpiFC01gDxgwVg9hOJbb2yOg7Ro9ReU/edit","8/27/2023"],
    ["snake game","https://studio.code.org/projects/applab/3497B6mHQEX01ytA8pirriRuWez-SICxGCAtP3qPUro/edit","12/30/2017"],
    ["3d bhavik","https://studio.code.org/projects/applab/ae9Ws5OMDaNsPX4vAvPAdIMmOsTxegNrHTItmEVETjg/edit","12/28/2017"],
    ["2048","https://studio.code.org/projects/applab/yiYrXKb-q89kZrgwh9CJKEfmSY4nXReXT9v5BJ2Bw94/edit","7/7/2017"],
]