window.data1=[["share Sudoku solver","https://studio.code.org/projects/applab/tq6f6xmxIqovL_yWTDpV0moGNpj5gC1yBz3GI2TfuII/edit","1/4/2025"],
["Binary Clock - MathEnthusiast314","https://studio.code.org/projects/applab/yk3e7kmByzzbixyx4zsC8_AnXJpSmnm8uozUwCpyKCU/edit","4/7/2023"],
["K Maps 2","https://studio.code.org/projects/applab/TlsrPjMWTiTWVvhnjx4R8fdNgk3n4Ht5T_vkUhxHLWU/edit","12/22/2022"],
["Exploring the universe","https://studio.code.org/projects/applab/4UKSctZTYKU9VNblcUUxLtTuNu4yAU3vBPiqeBEcpDM/edit","8/25/2021"],
["Final:Weather App","https://studio.code.org/projects/applab/GzxT43e2zd8V3bDaHglWFIhJ17Fu70csZPeKQHQ7Who/edit","3/23/2020"],
["Lights Out Game","https://studio.code.org/projects/applab/qlSdVVQrkwZ0jzpvpDeiwZ5reu-dNdoqi3VW0pzHjRw/edit","4/12/2020"],
["Systems of Equations using normal syntax","https://studio.code.org/projects/applab/F8cf7sdWAouRIpknq_GBQaXOVmPMeOnwm7b4k2cOvIc/edit","4/11/2020"],
["Remix: 3d Equation Evaluator trying draw lines","https://studio.code.org/projects/applab/HfGfcxBqYTo4vozZyqSinNlyIou7tOoqNuiAbIyb89U/edit","3/20/2020"],
["2d Graph","https://studio.code.org/projects/applab/kEUCxMdKd7P-a1y4zo4cO3IQasxWXeHipAoDwk1dS4w/edit","3/20/2020"],
["Connect Four for Login Multifeatured App","https://studio.code.org/projects/applab/r_RmJsgJ7GGUbgMHNkb7oSbNNgx4GP2wNOkYMqrB4_Q/edit","2/15/2020"],
["Final: SVG generator using Svg image(data:image) for Login Multifeatured App","https://studio.code.org/projects/applab/LrfR7bALNTQiJ9-zpnPCRNxt8aAAeAq8eyXyVuaxIFs/edit","3/10/2020"],
["Remix: Google Doodles","https://studio.code.org/projects/applab/KZWTTIuXEnXu3Pr2xf_yHJLXUyca_IEfCPA-VfcSVno/edit","3/8/2020"],
["concatenating Top View Images","https://studio.code.org/projects/applab/6EkvkpJAaFkqZi1H0zWDqFXmDKTdD1Wx7BJZu170Dxs/edit","11/12/2019"],
["Sudoku solver","https://studio.code.org/projects/applab/MKAGOH8k6Q3GK6Co_u69caCBc05ZXQJvUgYuRbr24Ek/edit","10/15/2018"],
["Ink Spill","https://studio.code.org/projects/applab/6W0jHpVDtTbcg3GhLOJrs-KI1c1P2Xo80bNtLBqHVzk/edit","6/9/2018"],
]